export const ALL_BILL_REQUEST = "ALL_BILL_REQUEST";
export const ALL_BILL_SUCCESS = "ALL_BILL_SUCCESS";
export const ALL_BILL_FAIL = "ALL_BILL_FAIL";

export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const CREATE_BILL_REQUEST = "CREATE_BILL_REQUEST";
export const CREATE_BILL_FAIL = "CREATE_BILL_FAIL";
